version: '3'
services:
    backend:
        build: 
            context: ./backend
            dockerfile: dockerfile.dev
        restart: unless-stopped
        ports:
            - "3001:3001"
networks:
    default:
        external: true
        name: tuxtum
