FROM node:16-alpine 

WORKDIR /project

RUN apk add --no-cache git

RUN git clone https://github.com/gambitmis/nodejs-login-example1.git

RUN npm init -y

RUN npm install bcrypt cookie-session ejs express express-validator mysql2 nodemon

EXPOSE 3001

CMD [ "node" , "index.js"] 